# Generated by Django 5.0.1 on 2025-05-03 09:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FileInstance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file_name", models.CharField(max_length=512)),
                ("file_hash", models.CharField(max_length=512)),
                ("file", models.FileField(blank=True, null=True, upload_to="documents/")),
            ],
        ),
        migrations.CreateModel(
            name="FileRevision",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("revision_number", models.IntegerField()),
                ("url", models.CharField(db_index=True, max_length=512)),
                (
                    "file",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="file_versions.fileinstance"),
                ),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name="FileVersion",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
