# Generated by Django 5.0.1 on 2025-05-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("file_versions", "0002_fileinstance_filerevision_delete_fileversion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileinstance",
            name="file_name",
            field=models.CharField(max_length=512, null=True),
        ),
    ]
